version: '3.6'

services:
    db:
        image: postgres:14-alpine
        restart: always
        env_file:
        - .env
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
